"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

from dotenv import load_dotenv

load_dotenv(BASE_DIR.parent / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")

# CSRF настройки для HTTPS
CSRF_TRUSTED_ORIGINS = list(
    filter(None, os.getenv("CSRF_TRUSTED_ORIGINS", "").split(","))
)

# Определение HTTPS за прокси (Nginx)
SECURE_PROXY_SSL_HEADER_VALUE = os.getenv("SECURE_PROXY_SSL_HEADER", "").split(",")
if len(SECURE_PROXY_SSL_HEADER_VALUE) == 2:
    SECURE_PROXY_SSL_HEADER = tuple(SECURE_PROXY_SSL_HEADER_VALUE)

INTERNAL_IPS = [
    "127.0.0.1",
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.github",
    "django_extensions",
    "resort.apps.ResortConfig",
    "users.apps.UsersConfig",
    "debug_toolbar",
    "django_filters",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "users.context_processors.auth_providers",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),  # имя сервиса базы данных в docker-compose.yml
        "PORT": os.getenv("DB_PORT"),
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_URL"),  # имя сервиса Redis в docker-compose.yml
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "Asia/Yekaterinburg"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Это префикс для всех статических файлов, которые используются в шаблонах HTML.
STATIC_URL = "/static/"

# Сюда собираются файлы при collectstatic
STATIC_ROOT = BASE_DIR / "staticfiles"

# Здесь Django ищет доп. статику
STATICFILES_DIRS = [BASE_DIR / "static"]

# По какому URL будут доступны загруженные медиафайлы.
MEDIA_URL = "/media/"

# Путь на файловой системе, где будут храниться загруженные медиафайлы.
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = "users:login"  # URL для перенаправления на страницу авторизации
LOGIN_REDIRECT_URL = "trip_list"  # Перенаправление после успешной авторизации
LOGOUT_REDIRECT_URL = "home"  # Перенаправление после выхода из системы
SITE_ID = 1

ACCOUNT_LOGIN_METHODS = {"username"}

ACCOUNT_SIGNUP_FIELDS = [
    "email*",
    "username*",
    "password1*",
    "password2*",
]

ACCOUNT_EMAIL_VERIFICATION = "optional"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

if DEBUG:
    # Использование консольного бэкенда для отправки писем (для разработки)
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 465))
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

FIXTURE_DIRS = [
    BASE_DIR / "fixtures",
]

# GitHub OAuth (опциональная фича)
GITHUB_CLIENT_ID = os.getenv("GITHUB_CLIENT_ID")
GITHUB_CLIENT_SECRET = os.getenv("GITHUB_CLIENT_SECRET")

# Включаем кнопку OAuth только если оба ключа установлены
GITHUB_LOGIN_ENABLED = bool(GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET)

# Настройки django-allauth
SOCIALACCOUNT_PROVIDERS = {
    "github": {
        "APP": {
            "client_id": GITHUB_CLIENT_ID,
            "secret": GITHUB_CLIENT_SECRET,
            "key": "",
        },
    }
}

# Django REST Framework settings
REST_FRAMEWORK = {
    # Форматы ответов по умолчанию
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",  # Для удобного просмотра в браузере
    ],
    # Пагинация по умолчанию
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    # Аутентификация (пока оставим базовую)
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",  # JWT аутентификация
        "rest_framework.authentication.SessionAuthentication",  # Для browsable API
    ],
    # Права доступа по умолчанию
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",  # Пока разрешаем всем (потом ограничим)
    ],
    # Фильтрация и сортировка и поиск по умолчанию
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",  # Фильтрация
        "rest_framework.filters.OrderingFilter",  # Сортировка
        "rest_framework.filters.SearchFilter",  # Поиск
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # Список классов для ограничения количества запросов
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    # Глобальные лимиты для каждого класса
    "DEFAULT_THROTTLE_RATES": {
        "anon": "10/minute",  # Гости - 10 запросов в минуту
        "user": "100/minute",  # Авторизованные - 100 запросов в минуту
    },
}

# Настройки для Simple JWT
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),  # Access токен живёт 15 минут
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),  # Refresh токен живёт 7 дней
    "ROTATE_REFRESH_TOKENS": True,  # Обновлять refresh при каждом использовании
    "BLACKLIST_AFTER_ROTATION": True,  # Старые токены в чёрный список
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),  # Формат: Authorization: Bearer <token>
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "SkiTrip Journal API",
    "DESCRIPTION": "API для журнала поездок на горнолыжные курорты России",
    "VERSION": "1.0.0",
    # Контакты
    "CONTACT": {
        "name": "Dmitriy Fomenko",
        "email": "d.fomenko95@gmail.com",
    },
    # Лицензия
    "LICENSE": {
        "name": "MIT License",
    },
    # Настройки UI
    "SERVE_INCLUDE_SCHEMA": False,  # Не показывать сырую схему
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,  # Сохранять токен после обновления страницы
        "displayOperationId": False,
    },
    # Группировка эндпоинтов по тегам
    "TAGS": [
        {"name": "auth", "description": "Аутентификация (JWT токены)"},
        {"name": "resorts", "description": "Горнолыжные курорты"},
        {"name": "trips", "description": "Поездки пользователей"},
        {"name": "media", "description": "Фотографии поездок"},
        {"name": "users", "description": "Пользователи"},
    ],
    # Схемы аутентификации
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": r"/api/",
}
