# Generated by Django 4.2.1 on 2025-12-19 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0002_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trip_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='resort.trip')),
            ],
        ),
    ]
