# Generated by Django 4.2.1 on 2025-12-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0003_tripmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=150),
        ),
    ]
