# Generated by Django 4.2.1 on 2025-12-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0004_resort_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
