# Generated by Django 4.2.1 on 2025-12-26 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resort', '0006_alter_resort_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resort',
            options={'verbose_name': 'Курорт', 'verbose_name_plural': 'Курорты'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-start_date'], 'verbose_name': 'Поездку', 'verbose_name_plural': 'Поездки'},
        ),
        migrations.AlterModelOptions(
            name='tripmedia',
            options={'verbose_name': 'Фотографию поездки', 'verbose_name_plural': 'Фотографии поездок'},
        ),
        migrations.AlterField(
            model_name='resort',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название курорта'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='region',
            field=models.CharField(max_length=100, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания поездки'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичная поездка'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='resort.resort', verbose_name='Курорт'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала поездки'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='tripmedia',
            name='image',
            field=models.ImageField(upload_to='trip_photos/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='tripmedia',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='resort.trip', verbose_name='Поездка'),
        ),
        migrations.AlterField(
            model_name='tripmedia',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
    ]
