# Generated by Django 6.0 on 2026-01-13 05:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0007_alter_resort_options_alter_trip_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Публичная поездка'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(db_index=True, verbose_name='Дата начала поездки'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['user', 'is_public'], name='resort_trip_user_id_2bc995_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['-start_date'], name='resort_trip_start_d_aab61b_idx'),
        ),
    ]
