# Generated by Django 5.1.4 on 2026-02-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resort", "0008_alter_trip_is_public_alter_trip_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripmedia",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="trip_photos/thumbnails/",
                verbose_name="Миниатюра",
            ),
        ),
    ]
